### ISSUE TITLE
Windows 10 Build Error "Cannot open include file: 'rtp.h': No such file or directory"

### ISSUE THREAD

**Issue by bootsie123** [medooze/rtmp-server-node#7]
Hi! I'm trying to install the module and I keep running into an issue when it's trying to build. I have installed the `windows-production-tools` too. Any ideas?

Error Message: `Cannot open include file: 'rtp.h': No such file or directory`

Command Logs:
```
PS C:\Users\John\Desktop\Programming\WebRTC-Test> npm install --save medooze-rtmp-server

 medooze-rtmp-server@0.6.3 install C:\Users\John\Desktop\Programming\WebRTC-Test\node_modules\medooze-rtmp-server
 test -f build/Release/medooze-rtmp-server.node || (node-gyp configure && node-gyp rebuild --jobs=max)

'test' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\John\Desktop\Programming\WebRTC-Test\node_modules\medooze-rtmp-server>if not defined npm_config_node_gyp (node "C:\Users\John\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-
bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure )  else (node "C:\Users\John\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" configure )

C:\Users\John\Desktop\Programming\WebRTC-Test\node_modules\medooze-rtmp-server>if not defined npm_config_node_gyp (node "C:\Users\John\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-
bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild --jobs=max )  else (node "C:\Users\John\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild --jobs=max )
  rtmp-server_wrap.cxx
  win_delay_load_hook.cc
..\src\rtmp-server_wrap.cxx(1034): warning C4996: 'v8::Value::ToObject': was declared deprecated [C:\Users\John\Desktop\Programming\WebRTC-Test\node_modules\medooze-rtmp-server\build\medooze-rtmp-server.vcxp
roj]
  c:\users\john\appdata\local\node-gyp\cache\10.16.0\include\node\v8.h(10046): note: see declaration of 'v8::Value::ToObject'
..\src\rtmp-server_wrap.cxx(1128): warning C4996: 'v8::Value::ToObject': was declared deprecated [C:\Users\John\Desktop\Programming\WebRTC-Test\node_modules\medooze-rtmp-server\build\medooze-rtmp-server.vcxp
roj]
  c:\users\john\appdata\local\node-gyp\cache\10.16.0\include\node\v8.h(10046): note: see declaration of 'v8::Value::ToObject'
..\src\rtmp-server_wrap.cxx(1223): warning C4311: 'type cast': pointer truncation from 'void *' to 'long' [C:\Users\John\Desktop\Programming\WebRTC-Test\node_modules\medooze-rtmp-server\build\medooze-rtmp-se
rver.vcxproj]
..\src\rtmp-server_wrap.cxx(1223): warning C4302: 'type cast': truncation from 'void *' to 'long' [C:\Users\John\Desktop\Programming\WebRTC-Test\node_modules\medooze-rtmp-server\build\medooze-rtmp-server.vcx
proj]
..\src\rtmp-server_wrap.cxx(1255): warning C4996: 'v8::Value::ToObject': was declared deprecated [C:\Users\John\Desktop\Programming\WebRTC-Test\node_modules\medooze-rtmp-server\build\medooze-rtmp-server.vcxp
roj]
  c:\users\john\appdata\local\node-gyp\cache\10.16.0\include\node\v8.h(10046): note: see declaration of 'v8::Value::ToObject'
..\src\rtmp-server_wrap.cxx(1275): warning C4996: 'v8::Value::ToObject': was declared deprecated [C:\Users\John\Desktop\Programming\WebRTC-Test\node_modules\medooze-rtmp-server\build\medooze-rtmp-server.vcxp
roj]
  c:\users\john\appdata\local\node-gyp\cache\10.16.0\include\node\v8.h(10046): note: see declaration of 'v8::Value::ToObject'
..\src\rtmp-server_wrap.cxx(1589): fatal error C1083: Cannot open include file: 'rtp.h': No such file or directory [C:\Users\John\Desktop\Programming\WebRTC-Test\node_modules\medooze-rtmp-server\build\medooz
e-rtmp-server.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\John\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\John\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--jobs=max"
gyp ERR! cwd C:\Users\John\Desktop\Programming\WebRTC-Test\node_modules\medooze-rtmp-server
gyp ERR! node -v v10.16.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm WARN webrtc-test@1.0.0 No description
npm WARN webrtc-test@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! medooze-rtmp-server@0.6.3 install: `test -f build/Release/medooze-rtmp-server.node || (node-gyp configure && node-gyp rebuild --jobs=max)`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the medooze-rtmp-server@0.6.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\John\AppData\Roaming\npm-cache\_logs\2020-05-08T02_21_09_531Z-debug.log
```

Npm Debug Log: https://pastebin.com/q5Qd6N01

**Comment by bootsie123** [comment]
Just noticed now that only MacOS and Linux are supported. Hopefully, Windows support will come in the future?
